server {
    listen 80;
    server_name talarc.ru www.talarc.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name talarc.ru www.talarc.ru;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/talarc.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/talarc.ru/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://datearc.maximkuznetsov612.workers.dev;
        proxy_set_header Host datearc.maximkuznetsov612.workers.dev;
        proxy_ssl_server_name on;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1000;

    expires 1y;
    add_header Cache-Control "public, immutable";
    location ~* \.(html)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
